#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Sep  2 15:53:42 2017

@author: abhilashakumari
"""

import os
os.chdir("/Users/abhilashakumari/downloads")
import urllib
import urllib.request

from bs4 import BeautifulSoup
theurl = "https://twitter.com/realDonaldTrump"
thepage = urllib.request.urlopen(theurl)
soup = BeautifulSoup(thepage,"html.parser")
i=0
#find all a , use find.all('a')
for link in soup.find_all('a'):
    print(link.get('href'))
    print(i)
    print(link)
    print(link.text)
    i=i+1
j=1
for link in soup.find_all("div",{"class":"js-tweet-text-container"}):
    print(j)
    print(link.text)
    j=j+1