#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Sep  2 15:13:02 2017

@author: abhilashakumari
"""
import requests
url = 'http://www.omdbapi.com/?apikey=ff21610b&t=Annabelle'
r= requests.get(url)
print(r.text)
json_data = r.json()
print(json_data)
for k in json_data.keys():
    print(k+':',json_data[k])