#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Sep  2 14:37:17 2017

@author: abhilashakumari
"""
import os
os.chdir("/Users/abhilashakumari/downloads")
import pandas as pd
file = open('moby_dick.txt',mode = 'r')
print(file.read())
print(file.closed)
file.close()
print(file.closed)
with open('moby_dick.txt')as file:
    print(file.readline())
    print(file.readlines()[6:8])
with open('moby_dick.txt')as file:
    print(file.readline())
    book=file.readlines()
len(book)
file = 'titanic.csv'
type(file)
df= pd.read_csv(file)
print(df)
df.head()
pd.DataFrame.hist(df.ix[:,4:5])
import matplotlib.pyplot as plt
plt.show()